local opts = { noremap = true, silent = true }
local keymap = vim.api.nvim_buf_set_keymap
keymap(0, "n", "gD", "<cmd>lua vim.lsp.buf.declaration()<CR>", opts)
keymap(0, "n", "gd", "<cmd>lua vim.lsp.buf.definition()<CR>", opts)
keymap(0, "n", "K", "<cmd>lua vim.lsp.buf.hover()<CR>", opts)
keymap(0, "n", "gI", "<cmd>lua vim.lsp.buf.implementation()<CR>", opts)
keymap(0, "n", "gr", "<cmd>lua vim.lsp.buf.references()<CR>", opts)
keymap(0, "n", "gl", "<cmd>lua vim.diagnostic.open_float()<CR>", opts)
keymap(0, "n", "<leader>lf", "<cmd>lua vim.lsp.buf.format{ async = true }<cr>", opts)
keymap(0, "n", "<leader>li", "<cmd>LspInfo<cr>", opts)
keymap(0, "n", "<leader>lI", "<cmd>LspInstallInfo<cr>", opts)
keymap(0, "n", "<leader>la", "<cmd>lua vim.lsp.buf.code_action()<cr>", opts)
keymap(0, "n", "<leader>lj", "<cmd>lua vim.diagnostic.goto_next({buffer=0})<cr>", opts)
keymap(0, "n", "<leader>lk", "<cmd>lua vim.diagnostic.goto_prev({buffer=0})<cr>", opts)
keymap(0, "n", "<leader>lr", "<cmd>lua vim.lsp.buf.rename()<cr>", opts)
keymap(0, "n", "<leader>ls", "<cmd>lua vim.lsp.buf.signature_help()<CR>", opts)
keymap(0, "n", "<leader>lq", "<cmd>lua vim.diagnostic.setloclist()<CR>", opts)
